name: ToDo CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-sast:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
            node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run SAST Lint
        run: npx eslint .

  build_and_deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Deploy to azure
        uses: Azure/functions-action@v1
        with:
          app-name: "DSOPipeline"
          package: '.'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
