name: push-grafana

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  push-grafana:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Push Metrics to Prometheus
        run: echo "github_actions_workflow_duration_seconds{workflow=\"${{ github.workflow }}\"} $(date +%s)" | curl http://localhost:9091/metrics